language: node_js
node_js:
  - "8.9.4"
before_install:
  - npm i -g npm@5.6.0
cache:
  directories:
    - node_modules
script:
  - npm run build
  - npm test
deploy:
  on:
    branch: master
  provider: s3
  access_key_id: "AKIAULEVJ7ELWOXS7T4C"
  secret_access_key: "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"
  bucket: "S3 Bucket"
  region: us-east-1
  skip_cleanup: true
  local_dir: build
  detect_encoding: true
  default_text_charset: "utf-8"
  dot_match: trueon:
after_deploy:
  # Allow `awscli` to make requests to CloudFront.
  - aws configure set preview.cloudfront true
  # Invalidate every object in the targeted distribution.
  - aws cloudfront create-invalidation --distribution-id E1J32G1NKE718D --paths "/*"