language: node_js
node_js:
  - "10.15.3"
before_install:
  - npm i -g npm@6.4.1
cache:
  directories:
    - node_modules
script:
  - npm run build
  - npm test
deploy:
  on:
    branch: master
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: "www.svyazhin.com"
  region: $AWS_DEFAULT_REGION
  skip_cleanup: true
  local_dir: build
  detect_encoding: true
  default_text_charset: "utf-8"
  dot_match: true
after_deploy:
  # Allow `awscli` to make requests to CloudFront.
  - aws configure set preview.cloudfront true
  # Invalidate every object in the targeted distribution.
  - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths /
